### ISSUE TITLE
3rd party issue. Analyzer::isSameHost fails to compare Host when SSL + zend-diactoros

### ISSUE THREAD

**Issue by basz** [neomerx/cors-psr7#12]
When the request header 'Host' value is in form of `Host: example.com` (without port) the parse_url method isn't capable of parsing the url correctly.

Feeding a url without a prefixed '\\' to parse_url will result in a non discovered domain name if the port is not present.

But I think a Host header in this form should parseable as url - or am I mistaking?

    Host: example.com

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23
https://github.com/neomerx/cors-psr7/blob/master/src/Analyzer.php#L256
https://github.com/neomerx/cors-psr7/blob/master/tests/Http/ParsedUrlTest.php#L59

**Comment by basz** [comment]
I should add that I'm using php-fpm and zendframework/zend-diactoros. Somehow they seem to loose the port number from the request Host header even when httpie tells me it sends it along in the request.

```
http --form POST https://api-development.s01.localhost:443/oauth/token grant_type="password" username="xxx" password="xxx" Origin:http://localhost:4200 --verify=no --style=friendly --print=HBhb 

POST /oauth/token HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 68
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: api-development.s01.localhost:443
Origin: http://localhost:4200
User-Agent: HTTPie/0.9.3
```

**Comment by neomerx** [comment]
@basz Default port seems to be supported. Have a look at [this test](https://github.com/neomerx/cors-psr7/blob/master/tests/Http/ParsedUrlTest.php#L33-L38).
Could it be you terminate SSL traffic on one node and then balance it to another with different port?

**Comment by neomerx** [comment]
@basz for the provided URL it will return
```php
        $url = $this->getUrlFromString('https://api-development.s01.localhost:443/oauth/token');
        $origin = $url->getOrigin();
```
Values would be
```
Neomerx\Cors\Http\ParsedUrl::__set_state(array(
   'scheme' => 'https',
   'host' => 'api-development.s01.localhost',
   'port' => 443,
   'urlAsString' => 'https://api-development.s01.localhost:443',
))

'https://api-development.s01.localhost:443'
```

Does it seem to be OK?

**Comment by basz** [comment]
That's fine, except that ['$hostHeaderValue[0]'](https://github.com/neomerx/cors-psr7/blob/master/src/Analyzer.php#L256) is `api-development.s01.localhost`.

then I get
```
        $hostHeaderValue = $request->getHeader(CorsRequestHeaders::HOST);
        var_export($hostHeaderValue);
        $hostUrl = empty($hostHeaderValue) === true ? null : $this->factory->createParsedUrl($hostHeaderValue[0]);
        var_export($hostUrl);die();


array (
  0 => 'api-plhw-development.s01.localhost',
)
Neomerx\Cors\Http\ParsedUrl::__set_state(array(
   'scheme' => NULL,
   'host' => NULL,
   'port' => 80,
   'urlAsString' => NULL,
))
```

ps. no balancer

**Comment by neomerx** [comment]
@basz it seems this line
```php
$hostHeaderValue = $request->getHeader(CorsRequestHeaders::HOST);
```
returns
```php
['api-plhw-development.s01.localhost']
```
instead of
```php
['api-plhw-development.s01.localhost:443']
```
according to [spec for Host](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23)

As you say you use `zend-diactoros` for `$request` it looks it either has a bug or you have another problem with it (I can't believe diactoros might have such a trivial bug but everything points to it so far).

**Comment by neomerx** [comment]
@basz Can you please dump `$request`? Out of curiosity if it did have `443` port originally.

**Comment by basz** [comment]
@neomerx You read the specs as Host *must* have port number? I can't read that stuff... :-/

ping @weierophinney

**Comment by neomerx** [comment]
@basz The very first line
> The Host request-header field specifies the Internet host **and port number**

**Comment by weierophinney** [comment]
The port is not required, if using the standard port for the given scheme. (We specifically mention that on the spec.)

**Comment by basz** [comment]
dump of request https://gist.github.com/basz/0408e7e72d4458afb008

**Comment by neomerx** [comment]
@weierophinney Agree for port 80 but @basz says it had 443 `api-development.s01.localhost:443`

**Comment by neomerx** [comment]
What I see in the dump
> 'REQUEST_SCHEME' => 'https',
    ...
    'SERVER_PORT' => '443',
    ...
      'HTTP_HOST' => 'api-plhw-development.s01.localhost',
...
      'HTTPS' => 'on',

@weierophinney Correct me if I'm wrong but `$request->getHeader('Host')` should return
```php
['api-plhw-development.s01.localhost:443']
```
shouldn't it?

**Comment by weierophinney** [comment]
Missed that this was SSL; yes, needs the port in this case.

**Comment by basz** [comment]
Ok I'll open an issue at diactoros then

But that would still mean that this issue would be valid for non https. Not that that should be support I guess.

> Op 8 mrt. 2016 om 00:50 heeft weierophinney <notifications@github.com> het volgende geschreven:
> 
> Missed that this was SSL; yes, needs the port in this case.

**Comment by neomerx** [comment]
@basz No matter what will be returned `host` or `host:80` from `$request->getHeader('Host')` it will be compared in canonical form (`host name` + `port`) in `Analyzer::isSameHost`
Can you please link the issue you are opening and I close this issue? Feel free to request reopen if any new problems are found.
