### ISSUE TITLE
Purpose of check 'Host' request?

### ISSUE THREAD

**Issue by tuupola** [neomerx/cors-psr7#19]
Regarding these lines labeled as [check 'Host' request](https://github.com/neomerx/cors-psr7/blob/master/src/Analyzer.php#L131-L140). What is the purpose of this part of the code? When should I use it?

I understand what it does but I cannot find where it belongs in the [CORS recommendation](https://www.w3.org/TR/cors/).

**Comment by neomerx** [comment]
6.3

> In addition to checking the Origin header, resource authors are strongly encouraged to also check the Host header....

**Comment by tuupola** [comment]
Just did not look hard enough. Thanks!
