### ISSUE TITLE
Allowing all headers should be removed

### ISSUE THREAD

**Issue by neomerx** [neomerx/cors-psr7#23]
Currently there is a config option `Settings::VALUE_ALLOW_ALL_HEADERS` which should allow all headers pass through CORS. It works fine for internal lib logic. No problem here. The problem is that this value `*` is actually sent to client in `Access-Control-Allow-Headers` and browser don't understand this value.

It looks the only possible way is listing all allowed headers and special `*` should be removed.

It was added mostly to make development easier. However since logging has been added to the lib this feature is not so important.

**It is recommended avoid using `Settings::VALUE_ALLOW_ALL_HEADERS` and just list all allowed headers in `Settings::KEY_ALLOWED_HEADERS`**

**Comment by neomerx** [comment]
Proposed solution: mark the constant as depreciated and do not sent it to client (it's not recognizable anyway).

**Comment by neomerx** [comment]
link here original idea https://github.com/neomerx/cors-psr7/issues/15

**Comment by barryvdh** [comment]
Allow all headers could just return all requested headers, right?

**Comment by neomerx** [comment]
@barryvdh It's related to [Access-Control-Allow-Headers](https://www.w3.org/TR/cors/#access-control-allow-headers-response-header) header. On `preflight request` CORS should reply with a list of headers it allows browser to send in the actual request (which comes right after the `preflight request`). Initially I thought it would be a good idea to allow all headers (mostly for debugging purposes). Though the spec do not have any possibilities to 'allow all headers'. They must be listed one by one.
As far as I understand your question you're asking what if sending back all the headers CORS received in [Access-Control-Request-Headers](https://www.w3.org/TR/cors/#http-access-control-request-headers). IMHO it would look as a security hole because it undermines the whole idea about 'allowed headers'. I found logging `Access-Control-Request-Headers` headers which are not allowed to be a better solution for debugging.

**Comment by neomerx** [comment]
@barryvdh BTW if you think it would be better to send all them back you can easily override it [here](https://github.com/neomerx/cors-psr7/blob/cc0413d6843ca27f90d15dbaf3bc6f9f972476f0/src/Analyzer.php#L291-L304).
