### ISSUE TITLE
What kind of check does `serServerOrigin` do?

### ISSUE THREAD

**Issue by starx** [neomerx/cors-psr7#27]
What kind of test does the following code does?

         $this->settings->setServerOrigin([
            'scheme' => 'http',
            'host'   => 'example.com',
            'port'   => 123,
        ])

To pass the checks, should the request be coming from `http://example.com` port 123 or to `http://example.com:123`?

I am trying to implement the library on Silex Framework and I am trying to match the request is coming to the one I am specifying, and it is not working. 

https://github.com/neomerx/cors-psr7/blob/24944f39483d1a89f66ae9d58cca9f82b8815b35/tests/AnalyzerTest.php#L62

**Comment by neomerx** [comment]
> What kind of test does the following code does?

This is an optional check for `Host` header recommended by [6.3 Security paragraph](https://www.w3.org/TR/cors/#resource-security) of the CORS spec.

> I am trying to implement the library on Silex Framework and I am trying to match the request is coming to the one I am specifying, and it is not working.

Either turn off the check during development or set a valid server origin your browser actually sending.

**Comment by starx** [comment]
@neomerx Thanks for the response. To confirm, if a siteA.com is trying to access resources on siteB.com, the `setServerOrigin` should define `siteA.com` as the host?

**Comment by neomerx** [comment]
siteB

**Comment by starx** [comment]
Thanks for the confirmation.
