### ISSUE TITLE
In some cases it incorrectly checks `Host` header

### ISSUE THREAD

**Issue by starx** [neomerx/cors-psr7#28]
I am trying to implement this as a middleware on Silex Framework (version 2). Silex by default does not support PSR 7 request and responses, so I use [DiactorosFactory](https://github.com/symfony/psr-http-message-bridge) Library to convert the Symfony Foundation Request/Response to & from PSR 7 Request and Response.

In the CORS Settings, I have something like this

    ->setServerOrigin([
        'scheme' => 'http',
        'host'   => 'www.something.test',
        'port'   => 80,
    ])

And the check fails even when the call is made to the host that is configured above i.e. `www.something.test`.

I am making a preflight request to `http://www.something.test` and when it comes to `Analyzer.php`'s `isSameHost` method `$host` get's value of `www.something.test` and `$hostURL` which should be parsed object, has `host` property as null. 

https://github.com/neomerx/cors-psr7/blob/24944f39483d1a89f66ae9d58cca9f82b8815b35/src/Analyzer.php#L320

This is the because internally it uses php's function `parse_url` to parse url if it is string.

https://github.com/neomerx/cors-psr7/blob/24944f39483d1a89f66ae9d58cca9f82b8815b35/src/Http/ParsedUrl.php#L64

and after parsing `www.something.test` returns array which looks like 

	array(..) {
	  ["path"]=>
	  string(5) "www.something.test"
	}

and thus does not have enough information to match the host.

https://github.com/neomerx/cors-psr7/blob/24944f39483d1a89f66ae9d58cca9f82b8815b35/src/Http/ParsedUrl.php#L71-L73

I am not sure why

https://github.com/neomerx/cors-psr7/blob/24944f39483d1a89f66ae9d58cca9f82b8815b35/src/Analyzer.php#L320-L321

`$host` where which returns `www.something.test` passed to `createParsedURL`  as it does not have enough data to properly parse all the request.

**Comment by starx** [comment]
If you use

        $host    = $this->getRequestHostHeader($request);
        $fullURL = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
        $hostUrl = $host === null ? null : $this->factory->createParsedUrl($fullURL);

to create the parsed URL. It is able to match the host correctly.

**Comment by neomerx** [comment]
To begin with, which browser sends `Host` header without HTTP Schema (e.g. `www.something.test`)?

**Comment by neomerx** [comment]
I can answer my own question. All browsers send the header without HTTP schema https://tools.ietf.org/html/rfc7230#section-5.4

OK, re-read the question. I don't get it yet.

**Comment by starx** [comment]
@neomerx I am not using browser to test this. I am using Insomnia (a rest client). It should not be different. It does send the request with full HTTP Schema. 

This line of code

https://github.com/neomerx/cors-psr7/blob/24944f39483d1a89f66ae9d58cca9f82b8815b35/src/Analyzer.php#L320-L321

Is only set to return the host. And the host does not have the full URL. In a link such as this `http://www.example.com` host is `www.example.com`. It should not bepassed to `createParsedURL` as it can't create URL from just the host information.

What does get returned in `$host` in your case?

**Comment by neomerx** [comment]
It looks like a bug. I'm surprised it has been living for such a long time :smile: 

In some cases, it incorrectly checks `Host` header. My observations

|server| Host header|
|--------|------------------|
|HTTP(80)|host.com|
|HTTPS(443)|host.com|
|HTTP(8080)|host.com:8080|

Firslty, it should be rechecked how `Host` header should be compared according to RFC.

Secondly, `parse_url` might work not as expected. If input parameter is just host (e.g. `host.com`) then it returns `host.com` as `path` and nothing in `host`. If port is added then it works as expected.

**Comment by starx** [comment]
@neomerx Yup. I think `parse_url` expects some parts of the URL to be present in order to parse correctly. Why not use solution similar to the one I [posted](https://github.com/neomerx/cors-psr7/issues/28#issuecomment-391332247)? That way parse_url works correctly and you can continue with matching.

**Comment by neomerx** [comment]
Neither [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host), nor [RFC](https://tools.ietf.org/html/rfc7230#section-5.4) tell anything definitive about header comparison. Browsers such as Firefox and Chrome do not add an optional port for HTTP (80) and HTTPS (443) so in practice, `Host` header should be compared just as a string value.

Currently, server origin/host setting expects 3 parameters: scheme, host, and port. I think it would be the right solution to ignore scheme and use the port in comparison only if it is specified in settings. So for a typical setting where the only host is specified, it would be just string values comparison.

**Comment by starx** [comment]
How would comparing only the port ensure that the server origin is correct? I think the comparison it does now is correct and provides maximum security, because it matches all the parts: scheme, host, and port.

**Comment by neomerx** [comment]
I meant 'to ignore scheme and use [host and] the port in comparison only if it is specified in settings'. Scheme is never sent so it doesn't make any sense to compare it. Port is also never sent neither for HTTP, nor for HTTPS which covers 99% cases.

**Comment by starx** [comment]
Oh! Makes sense. :)

**Comment by starx** [comment]
It is still not working for me. `$portOrNull = parse_url($host, PHP_URL_PORT);` resolves as `null`. `$this->getRequestHostHeader($request)` is still returning only the host part.

**Comment by starx** [comment]
Actually, I can see that port is only checked if it is set in the settings as you said in the previous comment (I forgot that). Please, consider my question answered. 😄
