### ISSUE TITLE
Creating Settings from an Array (Settings Factory)

### ISSUE THREAD

**Issue by fenric** [neomerx/cors-psr7#35]
Are you planning to create a factory for Settings?

For example:

```php
(new SettingsFactory)->createFromArray([
    'foo' => 'bar',
    'bar' => 'baz',
    'baz' => 'qux',
]);
```

I would like not to write this:

https://github.com/sunrise-php/awesome-skeleton/blob/master/src/Middleware/CorsMiddleware.php#L80

What are your thoughts on this?

**Comment by neomerx** [comment]
I think the best option for you would be having custom implementation for [AnalysisStrategyInterface](https://github.com/neomerx/cors-psr7/blob/0f968523b0b8215540915464aed08c5c4a4bf8b5/src/Contracts/AnalysisStrategyInterface.php#L27-L165). The library have no dependencies on any specific implementation but only on the interface. It will give you maximum flexibility and performance. You can use [default implementation](https://github.com/neomerx/cors-psr7/blob/0f968523b0b8215540915464aed08c5c4a4bf8b5/src/Strategies/Settings.php#L36-L648) as a reference. The great benefit we will not have to argue which param names are best and should they be CamelCase or snake_case :smile: 

If your only issue is a performance you can optimize it with a cache. `Settings` could be exported as a plain array and then cached. A new instance of `Settings` could be created very effectively [in just a couple of lines of code](https://github.com/neomerx/cors-psr7#settings).

Don't hesitate to ask any further questions.

**Comment by neomerx** [comment]
After looking into your profile I think the first option is the best for you. The implementation should be quite obvious but if you have any question don't hesitate to ask and :calling: if needed.

**Comment by fenric** [comment]
I understand you :)

But then, I will write a bridge for your package. I want less code in the application :)

Think about it ;)

**Comment by neomerx** [comment]
I think the size would be comparable AND you will get namings you like AND it will be faster. Though it's you to decide.

**Comment by neomerx** [comment]
If you have any further questions please don't hesitate to ask.
