### ISSUE TITLE
Can't extend Analyzer class

### ISSUE THREAD

**Issue by sunkan** [neomerx/cors-psr7#36]
Hi 

Thanks for an awesome library

Due to the use of `static::` in

https://github.com/neomerx/cors-psr7/blob/0f968523b0b8215540915464aed08c5c4a4bf8b5/src/Analyzer.php#L277

Because the class constants are private they can't be accessed from the child class. And when you extend the analyzer it will automatically try to use the child scope when using `static::` so it would work if you used `self::` in the Analyzer class.

Would you be open to a pull-request to fix this?

**Comment by neomerx** [comment]
Released in https://github.com/neomerx/cors-psr7/releases/tag/3.0.0
