### ISSUE TITLE
Small misleading in init factory method

### ISSUE THREAD

**Issue by ybelenko** [neomerx/cors-psr7#37]
Trying to setup package in PHP-DI container and seems like I've found small mistake in `init` method.

https://github.com/neomerx/cors-psr7/blob/0f968523b0b8215540915464aed08c5c4a4bf8b5/src/Strategies/Settings.php#L158-L159

Second `setAllowedOrigins([])` overwrites `areAllOriginsAllowed` to `false` value, then `enableAllOriginsAllowed()` makes no sense one line before.

**Comment by vbargl** [comment]
It took me quite some time before I notice that `setAllowedOrigins` sets `areAllOriginsAllowed` back to `false`.
Removing that line would make it more intuitive.

**Comment by neomerx** [comment]
Released in https://github.com/neomerx/cors-psr7/releases/tag/3.0.0
